### ISSUE TITLE
Count with predicate

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions.analyzers#11]
When using the Count method with a predicate overload the predicate is not taken into account.

```c#
list.Count(e => e > 1).Should().Be(2);
```
is simplified into:
```c#
list.Should().HaveCount(2);
```

**Comment by Meir017** [comment]
- [ ]  CollectionShouldHaveCountAnalyzer should work also for the lambda overload
- [ ]  Add `list.Count(e => e > 1).Should().Be(2);` to the docs https://github.com/fluentassertions/fluentassertions/blob/release-5.0/docs/_data/tips/collections.yml

**Comment by jnyrup** [comment]
If you're updating the docs, there is a related example in there:
```c#
- old: |
    actual.Where(x => x.SomeProperty).Should().HaveCount(1);
  new: |
    actual.Should().ContainSingle(x => x.SomeProperty);
```
https://github.com/fluentassertions/fluentassertions/blob/88c4fd6ff7c5444b46096553ea7bd2e3df804289/docs/_data/tips/collections.yml#L248

And I would probably replace
```c#
list.Count(e => e > 1).Should().Be(2);
```
with 
```c#
list.Where(e => e > 1).Should().HaveCount(2);
```

**Comment by dennisdoomen** [comment]
> When using the Count method with a predicate overload the predicate is not taken into account.

What do you mean with that? The `Count` is an LINQ extension method. The resulting `IEnumerable<T>` should return a lazy evaluated filter.

**Comment by Meir017** [comment]
@dennisdoomen he was talking about the analyzer...

I meant that I wanted to see if it was possible to rewrite the assertion using that overload

**Comment by jnyrup** [comment]
@dennisdoomen 
The "not taken in to account" is my attempt to blame the computer rather than @Meir017's great work.

When using The `Count` method from LINQ that takes an predicate, the simplified assertion produced by the analyzer no longer contains the predicate.
