### ISSUE TITLE
Fluentassertions.Analyzers 0.12.0 gives warning with net48

### ISSUE THREAD

**Issue by rastrup** [fluentassertions/fluentassertions.analyzers#114]
### Description

When using the Fluentassertions.Analyzers 0.12.0 in a project the following warnings appear in Visual Studio:

`Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.CollectionShouldBeEmptyAnalyzer cannot be created from C:\Users\KristianRastrup\.nuget\packages\fluentassertions.analyzers\0.12.0\analyzers\dotnet\cs\Release\netstandard2.1\FluentAssertions.Analyzers.dll: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Den angivne fil blev ikke fundet..	`

And: 

`Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.CollectionShouldBeInAscendingOrderAnalyzer cannot be created from C:\Users\KristianRastrup\.nuget\packages\fluentassertions.analyzers\0.12.0\analyzers\dotnet\cs\Release\netstandard2.1\FluentAssertions.Analyzers.dll: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Den angivne fil blev ikke fundet..`

The project is a .Net Framework 4.8 xUnit test project

### Complete minimal example reproducing the issue

Add FluentAssertions.Analyzers 0.12.0 to a .Net Framework 4.8 project as a NuGet package

### Expected behavior:

No warnings

### Actual behavior:

Warnings appear during build

### Versions

FluentAssertions.Analyzers 0.12.0 
.Net Framework 4.8

**Comment by Meir017** [comment]
try the new version `0.12.1`

**Comment by Corniel** [comment]
For me, this is not fixed:

Severity	Code	Description	Project	File	Line	Suppression State
>Warning CS8032
> An instance of analyzer FluentAssertions.Analyzers.* cannot be created from C:\Users\ *****\ .nuget\packages\fluentassertions.analyzers\0.12.1\analyzers\dotnet\cs\Release\netstandard2.1\FluentAssertions.Analyzers.dll: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

I'm using Visual Studio 2022 with .NET 6 (and .NET 5). Have the issue with multiple projects/solutions.

**Comment by Meir017** [comment]
@Corniel can you share a sample project please?

**Comment by Corniel** [comment]
> @Corniel can you share a sample project please?

Sure: this branch: https://github.com/Qowaiv/Qowaiv/tree/publish-v6

**Comment by maxkoshevoi** [comment]
Also having this issue with `.Net 6` project in `VS2022 17.1.0 Preview 1.0` (`FluentAssertions.Analyzers 0.12.1`)

**Comment by Meir017** [comment]
please continue here #117

**Comment by Meir017** [comment]
please try the new version `0.13.0`
