### ISSUE TITLE
Support .Net 6

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions.analyzers#117]
Let's add support for .Net 6 as well

**Comment by jnyrup** [comment]
Out of curiosity, what's the benefit of the additional target?
The downside is an increase in size of nupkg.

**Comment by Corniel** [comment]
@Meir017 seems to work now. Although I don't understand why. My own analyzer (https://www.nuget.org/packages/Qowaiv.Analyzers.CSharp) nor Sonar.Analyzer.CSharp have a .NET 6 target, but lack the issue.
