### ISSUE TITLE
HaveCount with special cases for 0 or 1

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions.analyzers#12]
This is really just a nice to have.

```c#
list.Count().Should().Be(0);
list.Count().Should().Be(1);
```
are correctly simplified into:
```c#
list.Should().HaveCount(0);
list.Should().HaveCount(1);
```

It would be nice, if they could be simplified directly into the `ContainSingle` and `BeEmpty` instead.

```c#
list.Should().ContainSingle();
list.Should().BeEmpty();
```

**Comment by Meir017** [comment]
right now it takes to code-fixes to get there since `list.Should().HaveCount(0);` triggers `CollectionShouldBeEmptyAnalyzer` that suggets `list.Should().BeEmpty();`.

it will be available next release
