### ISSUE TITLE
Should().Equals(object) should not be used

### ISSUE THREAD

**Issue by Corniel** [fluentassertions/fluentassertions.analyzers#120]
Equals does no do what people might think.

See: https://community.sonarsource.com/t/fluentassertion-should-and-equals-methods-shouldnt-be-used-together/38181

**Comment by Corniel** [comment]
@Meir017 I can test that. Both ways, you should advocate there I think. :)

**Comment by Meir017** [comment]
@Corniel that's exactly what the analyzer + code-fixer suggest here. basically never use `Equals` with fluent-assertions

**Comment by Corniel** [comment]
Thanx,. I'll report that.
