### ISSUE TITLE
Fluentassertions.Analyzers 0.13.0 gives warning with net6.0

### ISSUE THREAD

**Issue by undefined77** [fluentassertions/fluentassertions.analyzers#122]
### Description

Fluentassertions.Analyzers 0.12.0 or 0.13.0 gives warning with net6.0

### Complete minimal example reproducing the issue

Add FluentAssertions.Analyzers 0.12.0 or 0.13.0 to a .Net 6.0 project as a NuGet package

### Expected behavior:

No warnings

### Actual behavior:

Warnings appear during build

### Versions

FluentAssertions.Analyzers 0.12.0 or 0.13.0
.Net 6.0

**Comment by Meir017** [comment]
@undefined77 version `0.16.0` just released with this fixed
