### ISSUE TITLE
Fluentassertions.Analyzers >=0.12.0 gives warning with net5.0

### ISSUE THREAD

**Issue by webhelpadmin** [fluentassertions/fluentassertions.analyzers#124]
### Description

Fluentassertions.Analyzers 0.12.0 or 0.13.0 gives warning with net5.0

### Complete minimal example reproducing the issue

Add FluentAssertions.Analyzers 0.12.0 or 0.13.0 to a .Net 5.0 project as a NuGet package

### Expected behavior:

No warnings

### Actual behavior:

Warnings appear during build

### Versions

FluentAssertions.Analyzers 0.12.0 or 0.13.0
.Net 5.0

**Comment by Meir017** [comment]
@webhelpadmin  is this about `net5.0` or `net6.0`? not clear

**Comment by webhelpadmin** [comment]
Hi @Meir017 it is for .net 5.0

**Comment by CaringDev** [comment]
is this about" CS8034: Unable to load Analyzer assembly"? If so, this is still an issue, at least with SDK 6 targeting net5:
> CSC : warning CS8034: Unable to load Analyzer assembly C:\Users\<user>\.nuget\packages\fluentassertions.analyzers\0.15.0\analyzers\dotnet\cs\Release\net6.0\ref\FluentAssertions.Analyzers.dll : Could not load file or assembly 'FluentAssertions.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058) [C:\Path\To\Tests.csproj]

**Comment by Meir017** [comment]
@CaringDev @webhelpadmin I think I'm confused about the target-frameworks, it doesn't seem to me right to add so many target-frameworks.
can we just use the `net48` & `netstandard2.1` and maybe also the `net6.0`?

**Comment by CaringDev** [comment]
I would have thought so too... not sure how analyzers behave though. 🤷 It seems weird that https://github.com/webhelpadmin/fluentassertions.analyzers/commit/546d55e0051fee24adf6ef277ba0f90c7b39260d is needed at all.

**Comment by webhelpadmin** [comment]
Hi @Meir017 I have tried to update .net 5.0 app with the new version 0.15. And I have received the CS warnings. After I have cleaned the solution and restart VS all warnings disappears. If @CaringDev could confirm that warnings also disappears for his solutions, then I guess we could close this PR as it is not relevant anymore,  you.

**Comment by CaringDev** [comment]
As this seems to actually be a preview SDK issue, I'd say 'close'. If this reappeaars after 6.0.200 RTM I'll open another one.
Thank you!

**Comment by Meir017** [comment]
@CaringDev version `0.16.0` just released with this fixed
