### ISSUE TITLE
Making NuGet package non-transitive

### ISSUE THREAD

**Issue by iamdmitrij** [fluentassertions/fluentassertions.analyzers#148]
### Description

When installing `FluentAssertions.Analyzers` package via NuGet feed, package is transitive by default. Perhaps since it's an analyzer for development only, it's best to make it non-transitive with `PrivateAssets`?

### Complete minimal example reproducing the issue

Run `dotnet add package FluentAssertions.Analyzers --version 0.15.0` and check destination `.csproj` file.

### Expected behavior:

Project file content to be:

```
<PackageReference Include="FluentAssertions.Analyzers" Version="0.15.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

### Actual behavior:

Project file content as of now:
```
<PackageReference Include="FluentAssertions.Analyzers" Version="0.15.0" />
```

### Versions

Fluent Assertions Analyzers v0.15.0
.NET 6.0

**Comment by Meir017** [comment]
@iamdmitrij This package is used only for the testing projects, are you using this package in the application projects?

**Comment by iamdmitrij** [comment]
@Meir017. No, not really. It's a unspoken convention that development libraries should be installed as private dependencies by default. Most of popular analyzers on NuGet.org do implement this. It's no problem to manually edit package references to include `PrivateAssets`, but it doesn't come by default from NuGet.org feed.

**Comment by Meir017** [comment]
@iamdmitrij version `0.16.0` just released with this implemented

**Comment by iamdmitrij** [comment]
@Meir017, thank you. Works like a charm.
