### ISSUE TITLE
Lot of warnings after upgrading to 0.15.0

### ISSUE THREAD

**Issue by karelkral** [fluentassertions/fluentassertions.analyzers#149]
After upgrading FluentAssertions.Analyzers from 0.11.4 to 0.15.0, a lot of warnings (60) appears in Error list of Visual Studio 2022:

`Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.AssertAreNotEqualAnalyzer cannot be created from C:\Users\karel\.nuget\packages\fluentassertions.analyzers\0.15.0\analyzers\dotnet\cs\Release\net48\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.AssertAreNotEqualAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'..	Scia.Cid.AppServer.Tfs.Api.FunctionalTests		1	Active`

`Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.CollectionAssertAllItemsAreNotNullAnalyzer cannot be created from C:\Users\karel\.nuget\packages\fluentassertions.analyzers\0.15.0\analyzers\dotnet\cs\Release\net48\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.CollectionAssertAllItemsAreNotNullAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'..	Scia.Cid.AppServer.Tfs.Api.FunctionalTests		1	Active
`

Also, rebuild time of the solution (37 projects) increased from 20 sec to more the one minute. I suppose that this is caused by issue above. 

Clearing .NuGet cache and restoring all packages again does not help.
Reverting analyzers to 0.11.4 helps - warnings are gone and compile time is ok.
Could you give me some advice?

### Versions
* Fluent Assertions Analyzers: 0.15
* .Net Core 5.0, Rest API application
*  VS 2022 17.0.5

**Comment by Meir017** [comment]
can you share the details of the `csproj` file of the project? you should only add `fluentassertions.analyzers` as a dependency in your tests projects

**Comment by karelkral** [comment]
Today after updating to 0.15.0, the warning messages are slightly different. The compile-time remains increased.
```
Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.AssertAreNotEqualAnalyzer cannot be created from C:\Users\karel\.nuget\packages\fluentassertions.analyzers\0.15.0\analyzers\dotnet\cs\Release\netstandard2.1\FluentAssertions.Analyzers.dll: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the specified file..	Scia.Cid.AppServer.Tfs.Api.FunctionalTests		
```
CsProj and its dependencies:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\Shared\Scia.Cid.AppServer.Tfs.Api.Tests.props" />

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.17.0" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Flurl.Http" Version="3.2.0" />
    <PackageReference Include="FluentAssertions.Analyzers" Version="0.15.0" />
    <PackageReference Include="MartinCostello.Logging.XUnit" Version="0.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="5.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.categories">
      <Version>2.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xunit.SkippableFact">
      <Version>1.4.13</Version>
    </PackageReference>
    <PackageReference Include="Unity.Microsoft.DependencyInjection">
      <Version>5.11.5</Version>
    </PackageReference>
  </ItemGroup>

</Project>
```

Scia.Cid.AppServer.Tfs.Api.Tests.props
```
<Project >
  
  <!-- Shared props for TfsAppServer.Tests -->
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release;DeveStaging;Staging;DebugSingleThread</Configurations>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <AnalysisLevel>5.0</AnalysisLevel>
    <NoWarn>CA1014</NoWarn>
  </PropertyGroup>

  <Import Project=".\Scia.Cid.AppServer.Tfs.Configurations.props" />
    
  <ItemGroup>
    <Compile Include="..\..\Shared\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
  </ItemGroup>

</Project>
```

Scia.Cid.AppServer.Tfs.Configurations.props
```
<Project>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugSingleThread|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>TRACE;DEBUG;DebugSingleThread</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DeveStaging|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>DEBUG;TRACE;DeveStaging</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>Release</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Staging|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>Staging</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

</Project>
```

**Comment by EddyHaigh** [comment]
This issue looks to be affecting other project with different target framework versions, I've seen a net472 and net6 test projects showing these warnings (Both are SDK style csproj). You can reproduce this by installing the package on a new test project.

**Comment by maxkoshevoi** [comment]
**Note**: This might not be fixed yet. 
Seems like warnings appear after the package update, and disappear after VS relaunch.
So warnings still might occur after updating to `0.16.0` (or whatever it will be called), since old version was broken, but I hope they won't appear after `0.16.0` -> `0.17.0` update.
