### ISSUE TITLE
Version 0.17.3 doesn't seem to work

### ISSUE THREAD

**Issue by renzo-baasdam** [fluentassertions/fluentassertions.analyzers#174]
### Description

Version 0.17.3 doesn't seem to work.

For example 
```csharp
        int actual = 1;
        actual.Should().BeGreaterThan(0); //0.17.2 suggests actual.Should().BePositive(); 0.17.3 doesn't
```

In 0.17.3, am not able to get any analyzer to work. Also the in the NuGet package-manager in the description, fields seem to be missing compared to 0.17.2

### Versions

0.17.3 fluentassertions.analyzers
net7.0

**Comment by Meir017** [comment]
Fixed, released version `0.17.4`
