### ISSUE TITLE
Warnings related to an old version

### ISSUE THREAD

**Issue by bsalmeida** [fluentassertions/fluentassertions.analyzers#193]
### Description

After upgrading from version 0.17.2 to 0.19.1, I got the following warning messages related to the previous version:

Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.Xunit.AssertEqualAnalyzer cannot be created from C:\Users\user\.nuget\packages\fluentassertions.analyzers\0.19.1\analyzers\dotnet\cs\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.Xunit.AssertEqualAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=0.17.2.0, Culture=neutral, PublicKeyToken=null'..

Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.Xunit.AssertNotEqualAnalyzer cannot be created from C:\Users\user\.nuget\packages\fluentassertions.analyzers\0.19.1\analyzers\dotnet\cs\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.Xunit.AssertNotEqualAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=0.17.2.0, Culture=neutral, PublicKeyToken=null'..

Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.Xunit.AssertNotStrictEqualAnalyzer cannot be created from C:\Users\user\.nuget\packages\fluentassertions.analyzers\0.19.1\analyzers\dotnet\cs\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.Xunit.AssertNotStrictEqualAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=0.17.2.0, Culture=neutral, PublicKeyToken=null'..

Warning	CS8032	An instance of analyzer FluentAssertions.Analyzers.Xunit.AssertStrictEqualAnalyzer cannot be created from C:\Users\user\.nuget\packages\fluentassertions.analyzers\0.19.1\analyzers\dotnet\cs\FluentAssertions.Analyzers.dll: Could not load type 'FluentAssertions.Analyzers.Xunit.AssertStrictEqualAnalyzer' from assembly 'FluentAssertions.Analyzers, Version=0.17.2.0, Culture=neutral, PublicKeyToken=null'..

### Complete minimal example reproducing the issue

- Create a project using version 0.17.2
- Upgrade it to version 0.19.1

### Expected behavior:

No warnings.

### Actual behavior:

4 new warnings described above.

### Versions

* Which version of Fluent Assertions Analyzers are you using? **0.19.1**
* Which .NET runtime and version are you targeting? **.NET 7**

### Additional Information

Visual Studio Professional 17.6.2
FluentAssertions 6.11.0

I have cleaned Nuget Storage.
If I roll back to version 0.17.2, the warning messages disappear.

**Comment by Meir017** [comment]
@bsalmeida just to be sure, how was this fixed?

**Comment by maxisam** [comment]
I have the same problem. why is this closed?

**Comment by Meir017** [comment]
@maxisam can you share a minimal project to reproduce this?

**Comment by bsalmeida** [comment]
> @bsalmeida just to be sure, how was this fixed?

I have cleaned the solution a couple of times and it worked.
