### ISSUE TITLE
feature-request: Support for FixAllProvider

### ISSUE THREAD

**Issue by kimpenhaus** [fluentassertions/fluentassertions.analyzers#246]
### Description

We've added FluentAssertionAnalyzers recently to our codebase - which is brownfield. Lots of unit-tests use still the old asserts. The analyzers do a great job but its very painful to single fix all the recommendations... (still more than 3k)

Roslyn gives the opportunity to fix all oocurrences with the FixAll provider/fix: [FixAllProvider](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/FixAllProvider.md)

It would be great if the analyzers could support this and give one a more simple way to transform older projects (with less effort)

**Comment by Meir017** [comment]
@kimpenhaus just to be sure, multiple different diagnostics are being reported in multiple files? (to understand how to test this once I understand how to support this... :) )

**Comment by kimpenhaus** [comment]
@Meir017 yes absolutely

like:

- Assert.AreEqual
- Assert.IsTrue
- Assert.IsFalse
- Assert.AreSame
- Assert.IsNotNull

etc.

I assume these are all different daignostics having their own code-fix?

We have lots if these asserts spread acrosse different test files in the solution

<img width="2248" alt="image" src="https://github.com/fluentassertions/fluentassertions.analyzers/assets/575109/93c4da3b-5d6a-48c5-8f43-9511445e0bef">

Would be great to apply the code fix solution wide :)

**Comment by Meir017** [comment]
> I assume these are all different daignostics having their own code-fix?
Yes, I was thinking of reducing the amount of analyzers and have a single analyzer for mstest / xunit / tips. 
I'm not sure how useful each specific diagnostic is and I'm considering having one fir each testing framework abd a generic one for tips

> Would be great to apply each individual code fix solution wide
Are you able to apply a specific diagnostic code fix globally?

**Comment by Meir017** [comment]
@kimpenhaus starting with version `0.28.0` all of the fluent assertions analyzers are grouped into very few diagnostic IDs, one for general fluent-assertions issues, one for mstest/xunit/nunit(not yet)
