### ISSUE TITLE
Checklist of all tips and whether they have analyzers

### ISSUE THREAD

**Issue by Arithmomaniac** [fluentassertions/fluentassertions.analyzers#274]
Instead of tracking https://fluentassertions.com/tips/#improved-assertions piecemeal (e.g. #245) there should be an issue checklist in this repo with a here, with each suggested improvement listed as a task.

**Comment by Arithmomaniac** [comment]
If it is preferred to link to each analyzer when it exists on the "tips" page instead, I can create an issue in the main repo

**Comment by Meir017** [comment]
> Instead of tracking https://fluentassertions.com/tips/#improved-assertions piecemeal (e.g. #245) there should be an issue checklist in this repo with a here, with each suggested improvement listed as a task.

I was thinking of having a test project with test-cases for all of the different tips, it will serve as documentation and an integration test that runs `dotnet format`

**Comment by Meir017** [comment]
@Arithmomaniac I was thinking of something like this - 
![image](https://github.com/fluentassertions/fluentassertions.analyzers/assets/9786571/398423aa-8a77-4a15-8fe1-45e91bd5a82a)

https://github.com/fluentassertions/fluentassertions.analyzers/pull/307/files#diff-40f9cb87232fc6df6199d10de09342f50ff38d1f153bfa1c77e8b62e878494f8

this way the asserts are evaluated in the CI to make sure the old/new asserts have the same result

**Comment by Arithmomaniac** [comment]
@Meir017 I love it
