### ISSUE TITLE
Wrong description for `.Should().Contain()` and `.Should().NotContain()`

### ISSUE THREAD

**Issue by FantasyTeddy** [fluentassertions/fluentassertions.analyzers#301]
### Description

The current descriptions for these two analysis rules is wrong:

| Rule | Actual | Expected |
| --- | --- | --- |
| [FAA0001](https://fluentassertions.com/tips/#Collections-19) | Use `.Should().NotBeEmpty()` | Use `.Should().Contain()` |
| [FAA0001](https://fluentassertions.com/tips/#Collections-20) | Use `.Should().BeEmpty()` | Use `.Should().NotContain()` |

### Complete minimal example reproducing the issue

```csharp
// Act
var actual = new List<int> {0};

// Assert
actual
    .Where(x => x <= 0)
    .Should().NotBeEmpty();
// or
actual
    .Where(x => x > 0)
    .Should().BeEmpty();
```

### Versions

* Fluent Assertions Analyzers version: **0.29.1**
* .NET Runtime/Target: **.NET 8**

**Comment by Meir017** [comment]
@FantasyTeddy thanks for reporting this!
