### ISSUE TITLE
support for exceptions assertions

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions.analyzers#31]
https://fluentassertions.com/tips/#exceptions

**Comment by Meir017** [comment]
@jnyrup I was thinking of adding cases for 

* `...Message.Should().Be("errorCode1");` => `.WithMessage("errorCode1");`
* `...Message.Should().StartWith("errorCode1");` => `...WithMessage("errorCode1*");`
* `...Message.Should().EndWith("errorCode1");` => `...WithMessage("*errorCode1");`

does this make sense?

**Comment by jnyrup** [comment]
I think it makes perfect sense.
It improves the failure message a bit and is shorter to write.

Any concerns you would like a second opinion about?

**Comment by Meir017** [comment]
I just wanted to be sure I'm not overthinking it
