### ISSUE TITLE
how to get started on large code base ?

### ISSUE THREAD

**Issue by fforjan** [fluentassertions/fluentassertions.analyzers#378]
### Description

I would like to introduce the fluentanalyzer in our large code base.
But we have too many issues - plenty of years of not so great assertings - they are not bad but it could better :)

The  issue is that all code errors are flagged as FAA001 so I cannot add the analyzer to all my test projects and enable one 'rule' at a time.
For example, I would like to start with the foo.Count.Should().Be(0) with foo.ShouldBeEmpty() but there is no option to simply do a first checkin with this fix first and disable all the other issues ?

Could we change that all errors are flagged with their own error code so that we can pick what we want to enable incrementally ?

**Comment by Meir017** [comment]
@fforjan Currently there's no support for this, this was changed a while back on purpose to allow refactoring all of the fluent-assertion analyzers tips with a single `dotnet format` command

I'm wondering what would be the most effective way to achieve this, maybe using a similar approach to https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md and define a txt configuration file that will contain multiple lines where each line is a name of a flow of the `FluentAssertionsAnalyzer` (each property in https://github.com/fluentassertions/fluentassertions.analyzers/blob/14bab81d847d79ddc17d156702bb1c2f2d7efac4/src/FluentAssertions.Analyzers/Tips/DiagnosticMetadata.cs#L5 represents a different case)

**Comment by fforjan** [comment]
So the approach i'm getting is to work project per project instead of working rule per rule across all projects - we have 200 projects in our solution, including ~70 unit tests projects.

In that case, there is a chunk of manageable work to be done for different tasks (and thus different commits).
Also we are in Visual Studio - one solution for our product, .NET Framework, native and installer projects- and we've seen the fixer failing when we work at the solution level. We are not using dotnet format but visual studio to fix everything and we've seen some crashes.
So by working in the end project per project, seems it allows us to be more efficient in the end.

**Comment by Meir017** [comment]
@fforjan are you able to share some code samples from the projects that caused the crashes?

**Comment by fforjan** [comment]
@Meir017   by going project per project, I should be able to isolate and provide code samples
