### ISSUE TITLE
Dictionary access incorrectly triggers CollectionShouldHaveElementAt suggestion

### ISSUE THREAD

**Issue by samcragg** [fluentassertions/fluentassertions.analyzers#44]
I'm using FluentAssertions version 5.4.0 and FluentAssertions.Analyzers version 0.10.1. When I create a test that asserts the values in dictionaries, the analyzer incorrectly suggests I use `HaveElementAt` which doesn't compile, i.e. given this code:

``` c#
[Fact]
public void DictionaryTest()
{
    var dictionary = new Dictionary<string, int> { ["123"] = 123 };
    dictionary["123"].Should().Be(123);
}
```

The analyzer incorrectly suggests:

```c#
[Fact]
public void DictionaryTest()
{
    var dictionary = new Dictionary<string, int> { ["123"] = 123 };
    dictionary.Should().HaveElementAt("123", 123);
}
```

Perhaps it could suggest (though it's not simplifying but is more idiomatic):

``` c#
dictionary.Should().ContainKey("123").WhichValue.Should().Be(123);
```

Happy to take a stab at a PR

**Comment by jnyrup** [comment]
Just as a note.
Fluent Assertions also has a shorthand for 
```csharp
dictionary.Should().ContainKey(key).WhichValue.Should().Be(value);
```

```csharp
dictionary.Should().Contain(key, value);
```

See https://fluentassertions.com/documentation/#dictionaries

**Comment by Meir017** [comment]
@samcragg I'll be happy to receive a pull-request for this 😄 

I think the solution should be to make the `CollectionShouldHaveElementAtAnalyzer` class (or even `CollectionAnalyzer`) method `ShouldAnalyzeVariableType` be more strict and exclude `Dictionary`
