### ISSUE TITLE
Writing to System.Console should not throw an exception

### ISSUE THREAD

**Issue by ErikSchierboom** [fluentassertions/fluentassertions.analyzers#49]
If I run the analyzers on this code:

```csharp
public class TestClass
{
    public static void Main()
    {
        System.Console.WriteLine();
    }
}
```

A null-reference exception is thrown.

**Comment by ErikSchierboom** [comment]
Note: I've created this issue to be able to refer to it in PR #48.

**Comment by Meir017** [comment]
@ErikSchierboom just released 0.10.3 check it out 😄

**Comment by ErikSchierboom** [comment]
@Meir017 Cool, I'll check it out!

**Comment by ErikSchierboom** [comment]
@Meir017 It's working now! Thanks a lot.
