### ISSUE TITLE
Remove codefix for Should().BeNull().And.BeEmpty()

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions.analyzers#74]
based on @jnyrup's comment https://github.com/fluentassertions/fluentassertions/pull/873#issuecomment-402947331

**Comment by jnyrup** [comment]
While `BeNull().And.BeEmpty()` is not equivalent to `BeNullOrEmpty()`, it might be a fine analyzer to detect those, and just warn that is does not make sense.
